services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: landing_saas
      POSTGRES_USER:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rustfs:
    image: rustfs/rustfs:latest
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
    ports:
      - "9000:9000"
    volumes:
      - rustfs-data:/data

volumes:
  postgres-data:
  rustfs-data:
