"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUp, ChevronRight, ChevronUp, Globe, House, Image as ImageIcon, ImagePlus, Monitor, Package, Paintbrush, Palette, Save, Smartphone, Trash2, Type as TypeIcon } from "lucide-react";
import { AdminNotice, AdminPageHeader } from "@/components/admin-ui";
import { notifyError, notifySuccess } from "@/lib/internal-notifications";
import { useDirtyForm } from "@/components/use-dirty-form";
import { visualSettingsFromStore, type VisualSettings, type VisualStore } from "@/lib/design-settings";
import { publicStoreTemplates, storeTemplateLabels } from "@/lib/catalog";
import { HomeSectionsEditor } from "@/components/home-sections-editor";
import { createBannerItem, getBannerItems } from "@/lib/public-page-config";
import { uploadImagesDirect, validateSelectedImage } from "@/lib/image-upload-client";
import type { ImageReference } from "@/lib/image-upload-contract";
import "./design-template-cards.css";
import "./design-overrides.css";

type ImageDraft={url:string;file?:File};
const sections=[["marca","Logo y favicon",ImageIcon],["colores","Colores de tu tienda",Palette],["tipografia","Tipo de letra / Íconos",TypeIcon],["encabezado","Encabezado",ArrowUp],["inicio","Página de inicio",House],["productos","Productos",Package],["pie","Pie de página",ArrowDown],["plantilla","Plantilla",Paintbrush]] as const;
export function DesignEditor({store,categories,products}:{store:VisualStore&{slug:string;updatedAt:string;hasDraft:boolean};categories:Array<{id:string;name:string;parentId?:string|null}>;products:Array<{id:string;name:string}>}){
 const [draft,setDraft]=useState(()=>visualSettingsFromStore(store));
 const [saved,setSaved]=useState(()=>JSON.stringify(draft));
 const [version,setVersion]=useState(store.updatedAt);
 const [hasDraft,setHasDraft]=useState(store.hasDraft);
 const [images,setImages]=useState<{logo:ImageDraft[];favicon:ImageDraft[];hero:ImageDraft[]}>({logo:store.logoUrl?[{url:store.logoUrl}]:[],favicon:store.faviconUrl?[{url:store.faviconUrl}]:[],hero:store.heroImageUrls.map(url=>({url}))});
 const [savedImages,setSavedImages]=useState(()=>JSON.stringify(images));
 const [sectionFiles,setSectionFiles]=useState<Record<string,File>>({});
 const [section,setSection]=useState<(typeof sections)[number][0]>("marca");
 const [sectionOpen,setSectionOpen]=useState(false);
 const [homeEditingSectionId,setHomeEditingSectionId]=useState<string|null>(null);
 const [mobileEditorOpen,setMobileEditorOpen]=useState(false);
 const [mobileEditorExpanded,setMobileEditorExpanded]=useState(false);
 const [preview,setPreview]=useState(false);const [device,setDevice]=useState<"desktop"|"mobile">("desktop");
 const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const frame=useRef<HTMLIFrameElement>(null);
 const localUrls=useRef<string[]>([]);
 useEffect(()=>()=>localUrls.current.forEach(url=>URL.revokeObjectURL(url)),[]);
 const dirty=JSON.stringify(draft)!==saved||JSON.stringify(images)!==savedImages||Object.values(images).some(list=>list.some(image=>image.file))||Object.keys(sectionFiles).length>0;
 useDirtyForm(dirty);
 const update=(patch:Partial<VisualSettings>)=>setDraft(current=>({...current,...patch}));
 const design=(patch:Partial<VisualSettings["designConfig"]>)=>update({designConfig:{...draft.designConfig,...patch}});
 const page=(patch:Partial<VisualSettings["publicPageConfig"]>)=>update({publicPageConfig:{...draft.publicPageConfig,...patch}});
 const sendPreview=useCallback(()=>{frame.current?.contentWindow?.postMessage({type:"design-preview",...draft,logoUrl:images.logo[0]?.url??null,heroImageUrls:images.hero.map(i=>i.url)},window.location.origin);},[draft,images]);
 useEffect(()=>{sendPreview();}); // Re-send after controls or the frame mode changes.
 useEffect(()=>{
  function ready(event:MessageEvent){if(event.origin===window.location.origin&&event.source===frame.current?.contentWindow&&event.data?.type==="design-preview-ready")sendPreview();}
  window.addEventListener("message",ready);
  return ()=>window.removeEventListener("message",ready);
 },[sendPreview]);
 function openMobileEditor(){setPreview(false);setSectionOpen(false);setMobileEditorOpen(true);setMobileEditorExpanded(false);}
 function closeMobileEditor(){setMobileEditorOpen(false);setSectionOpen(false);setHomeEditingSectionId(null);setMobileEditorExpanded(false);}
 function openSection(key:(typeof sections)[number][0]){setSection(key);setSectionOpen(true);setHomeEditingSectionId(null);setMobileEditorExpanded(true);}
 function backToSections(){if(section==="inicio"&&homeEditingSectionId){setHomeEditingSectionId(null);return;}setSectionOpen(false);}
 function selectImage(kind:keyof typeof images,file:File){const validation=validateSelectedImage(file);if(validation){setError(validation);return;}const url=URL.createObjectURL(file);localUrls.current.push(url);setImages(current=>({...current,[kind]:kind==="hero"?[...current.hero,{url,file}].slice(0,3):[{url,file}]}));}
 function removeImage(kind:keyof typeof images,index:number){setImages(current=>({...current,[kind]:current[kind].filter((_,i)=>i!==index)})); if(kind==="hero")update({heroImages:draft.heroImages.filter((_,i)=>i!==index)});else update({[kind]:null});}
 function pickSectionImage(sectionId:string,kind:"banner"|"category",target:string,file:File){const validation=validateSelectedImage(file);if(validation){setError(validation);return;}const url=URL.createObjectURL(file);localUrls.current.push(url);setSectionFiles(current=>({...current,[url]:file}));setDraft(current=>({...current,publicPageConfig:{...current.publicPageConfig,homeSections:current.publicPageConfig.homeSections.map(section=>{
  if(section.id!==sectionId)return section;
  if(kind==="banner")return {...section,bannerItems:[...getBannerItems(section),createBannerItem(url,crypto.randomUUID())],images:[]};
  const tiles=section.categoryTiles??(section.categoryIds.length?section.categoryIds.map((categoryId,index)=>({id:`legacy-${index+1}`,categoryId,title:"",imageUrl:section.categoryImages[categoryId]??""})):categories.filter(category=>!category.parentId).map((category,index)=>({id:`root-${index+1}-${category.id}`,categoryId:category.id,title:"",imageUrl:section.categoryImages[category.id]??""})));
  return {...section,categoryTiles:tiles.map(tile=>tile.id===target?{...tile,imageUrl:url}:tile),categoryIds:[]};
 })}}));}
 async function save(publish:boolean){setBusy(true);setError("");try{
 const references=async(kind:keyof typeof images):Promise<ImageReference[]>=>{const list=images[kind];const uploaded=await uploadImagesDirect(list.filter(i=>i.file).map(i=>({scope:kind==="hero"?"hero" as const:"logos" as const,file:i.file!})));let index=0;return list.map(i=>i.file?uploaded[index++]:{kind:"stored",url:i.url});};
 const logo=await references("logo"),favicon=await references("favicon"),heroImages=await references("hero");
 const activeSectionUrls=[...new Set(draft.publicPageConfig.homeSections.flatMap(section=>[...section.images,...(section.bannerItems??[]).map(item=>item.imageUrl),...Object.values(section.categoryImages),...(section.categoryTiles??[]).map(tile=>tile.imageUrl).filter(Boolean)]))].filter(url=>sectionFiles[url]);
 const uploaded=await uploadImagesDirect(activeSectionUrls.map(url=>({scope:"hero" as const,file:sectionFiles[url]})));
 const homeImages=Object.fromEntries(activeSectionUrls.map((url,index)=>[url,uploaded[index]]));
 const response=await fetch("/api/admin/design-draft",{method:publish?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,logo:logo[0]??null,favicon:favicon[0]??null,heroImages,homeImages,expectedUpdatedAt:version})});
 const result=await response.json();if(!response.ok)throw Error(result.error);
 const next=visualSettingsFromStore(result.store);setDraft(next);setSaved(JSON.stringify(next));setVersion(result.store.updatedAt);setHasDraft(!publish);
 setSectionFiles({});
 const nextImages={logo:result.store.logoUrl?[{url:result.store.logoUrl}]:[],favicon:result.store.faviconUrl?[{url:result.store.faviconUrl}]:[],hero:result.store.heroImageUrls.map((url:string)=>({url}))};setImages(nextImages);setSavedImages(JSON.stringify(nextImages));
 notifySuccess(publish?"Diseño publicado. Ya se ve en tu tienda.":"Borrador guardado. Tu tienda publicada no cambió.");
 }catch(error){notifyError(error instanceof Error?error.message:"No se pudo guardar. Tus cambios se conservan.");}finally{setBusy(false);}}
 function imagePicker(kind:keyof typeof images,label:string){return <div className="design-image-field"><h3>{label}</h3>{images[kind].map((image,index)=><div className="design-image" key={image.url}><img src={image.url} alt={label}/>{kind==="hero"&&index>0&&<button className="admin-icon-button" aria-label="Subir imagen" onClick={()=>setImages(current=>{const hero=[...current.hero];[hero[index-1],hero[index]]=[hero[index],hero[index-1]];return {...current,hero};})}><ArrowUp size={16}/></button>}<button className="admin-icon-button" aria-label={"Quitar "+label} onClick={()=>removeImage(kind,index)}><Trash2 size={16}/></button></div>)}{(kind!=="hero"||images.hero.length<3)&&<label className="design-upload"><ImagePlus size={18}/>{images[kind].length&&kind!=="hero"?"Cambiar imagen":"Subir imagen"}<input className="design-upload-input" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0];if(file)selectImage(kind,file);e.target.value="";}}/></label>}</div>;}
 const toggle=(label:string,checked:boolean,onChange:(checked:boolean)=>void)=><label className="design-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>;
 const color=(label:string,value:string,onChange:(value:string)=>void,description?:string)=><label className="design-color-field"><input type="color" aria-label={label} value={value} onChange={e=>onChange(e.target.value)}/><span><strong>{label} ({value.toUpperCase()})</strong>{description&&<small>{description}</small>}</span></label>;
 const surface=(key:"headerColors"|"announcementColors"|"footerColors",title:string)=><div className="grid gap-3"><h3 className="!text-base !font-semibold">{title}</h3><select className="field" aria-label={title} value={draft.designConfig[key].mode} onChange={e=>design({[key]:{...draft.designConfig[key],mode:e.target.value as "primary"|"secondary"|"background"|"custom"}})}><option value="primary">Usar color primario</option><option value="secondary">Usar color secundario</option><option value="background">Usar color de fondo y texto</option><option value="custom">Usar colores personalizados</option></select>{draft.designConfig[key].mode==="custom"&&<div className="grid gap-3">{color("Color de fondo",draft.designConfig[key].background,value=>design({[key]:{...draft.designConfig[key],background:value}}))}{color("Color del texto",draft.designConfig[key].text,value=>design({[key]:{...draft.designConfig[key],text:value}}))}</div>}</div>;
 return <div className="design-editor" aria-busy={busy}>
 <AdminPageHeader title="Diseño de la tienda" description="Personalizá, previsualizá y publicá cuando esté listo." action={<Link className="btn-secondary" href={"/"+store.slug} target="_blank">Ver tienda ↗</Link>}/>
 <div className="design-toolbar">
 <div className="design-toolbar-meta"><Link className="design-return" href="/gestion">← Ir a gestión</Link><span className={"admin-badge design-status "+(dirty?"warning":hasDraft?"purple":"success")} aria-live="polite" aria-atomic="true">{dirty?"Cambios sin guardar":hasDraft?"Borrador guardado":"Diseño publicado"}</span></div>
  <div className="design-toolbar-actions"><button type="button" className="btn-secondary design-save-action" disabled={busy||!dirty} onClick={()=>void save(false)}><Save className="design-mobile-icon" size={17} aria-hidden="true"/>Guardar borrador</button><button type="button" className="btn-primary design-publish-action" disabled={busy||(!dirty&&!hasDraft)} onClick={()=>void save(true)}><Globe className="design-mobile-icon" size={17} aria-hidden="true"/>{busy?"Guardando…":<><span className="design-desktop-label">Publicar cambios</span><span className="design-mobile-label">Publicar</span></>}</button></div>
 </div>
 <AdminNotice error>{error}</AdminNotice>
 <div className={"design-workspace "+(preview?"show-preview":"show-controls")+(sectionOpen?" editing-section":"")+(mobileEditorOpen?" mobile-editor-open":"")+(mobileEditorExpanded?" mobile-editor-expanded":"")}><aside id="design-controls" className={"design-controls"+(mobileEditorOpen?" mobile-editor-open":"")+(mobileEditorExpanded?" mobile-editor-expanded":"")} aria-label="Controles de diseño">
  <div className="design-sheet-toolbar"><button type="button" className="design-sheet-back" hidden={!sectionOpen} onClick={backToSections}>Regresar</button><span className="design-sheet-spacer" hidden={sectionOpen} aria-hidden="true"/><button type="button" className="design-sheet-expand" aria-label={mobileEditorExpanded?"Contraer panel de edición":"Expandir panel de edición"} aria-expanded={mobileEditorExpanded} aria-controls="design-controls" onClick={()=>setMobileEditorExpanded(value=>!value)}><ChevronUp size={19}/></button><button type="button" className="design-sheet-close" onClick={closeMobileEditor}>Cerrar</button></div>
  <nav aria-label="Secciones del diseño" hidden={sectionOpen}>
   <h2>Imagen de la marca</h2>
   {sections.slice(0,3).map(([key,label,Icon])=><button type="button" className="design-section-link" key={key} onClick={()=>openSection(key)}><Icon size={18} aria-hidden="true"/><span>{label}</span><ChevronRight size={17} aria-hidden="true"/></button>)}
   <h2>Apariencia de la tienda</h2>
   {sections.slice(3).map(([key,label,Icon])=><button type="button" className="design-section-link" key={key} onClick={()=>openSection(key)}><Icon size={18} aria-hidden="true"/><span>{label}</span><ChevronRight size={17} aria-hidden="true"/></button>)}
  </nav>
  <div className="design-fields admin-form-grid" hidden={!sectionOpen}><button type="button" className="design-section-back" onClick={backToSections}>Regresar</button>{!(section==="inicio"&&homeEditingSectionId)&&<h2 tabIndex={-1}>{sections.find(([key])=>key===section)?.[1]}</h2>}
 {section==="marca"&&<>{imagePicker("logo","Logo de tu negocio")}{imagePicker("favicon","Ícono de la pestaña")}<label>Tamaño del logo: {draft.designConfig.logoSize}px<input type="range" min={32} max={96} value={draft.designConfig.logoSize} onChange={e=>design({logoSize:Number(e.target.value)})}/></label><p className="text-xs text-muted">El nombre y los datos de tu negocio se editan en <Link className="text-brand underline" href="/gestion/configuracion/general">Configuración general</Link>.</p></>}
 {section==="colores"&&<>{toggle("Usar colores de la plantilla",draft.useTemplateColors,checked=>update({useTemplateColors:checked}))}{!draft.useTemplateColors&&color("Color primario",draft.primary,value=>update({primary:value}),"Resalta botones y textos importantes.")}{color("Contraste primario",draft.designConfig.primaryContrast??"#ffffff",value=>design({primaryContrast:value}),"Texto sobre el color primario.")}{!draft.useTemplateColors&&color("Color secundario",draft.accent,value=>update({accent:value}),"Elementos complementarios y promociones.")}{color("Contraste secundario",draft.designConfig.secondaryContrast??"#242424",value=>design({secondaryContrast:value}),"Texto sobre el color secundario.")}<h3>Colores de texto</h3>{color("Color de fondo",draft.designConfig.backgroundColor,value=>design({backgroundColor:value}),"Fondo general de la página.")}{color("Color de texto general",draft.designConfig.textColor,value=>design({textColor:value}),"Texto sobre el fondo general.")}{surface("headerColors","Colores del encabezado")}{surface("announcementColors","Colores de barra de anuncio")}{surface("footerColors","Colores del pie de página")}</>}
 {section==="tipografia"&&<><label>Tipografía<select className="field" value={draft.designConfig.font} onChange={e=>design({font:e.target.value as VisualSettings["designConfig"]["font"]})}><option value="template">Original de la plantilla</option><option value="serif">Editorial · Serif</option><option value="sans">Moderna · Sans</option><option value="rounded">Amigable · Redondeada</option></select></label><label>Trazo de los íconos<select className="field" value={draft.designConfig.iconStyle} onChange={e=>design({iconStyle:e.target.value as "thin"|"regular"|"bold"})}><option value="thin">Fino</option><option value="regular">Regular</option><option value="bold">Grueso</option></select></label></>}
 {section==="encabezado"&&<>{toggle("Mantener encabezado visible",draft.designConfig.headerSticky,checked=>design({headerSticky:checked}))}{toggle("Mostrar anuncio",draft.publicPageConfig.announcement.enabled,enabled=>page({announcement:{...draft.publicPageConfig.announcement,enabled}}))}{draft.publicPageConfig.announcement.enabled&&<label>Texto del anuncio<input className="field" maxLength={120} value={draft.publicPageConfig.announcement.text} onChange={e=>page({announcement:{...draft.publicPageConfig.announcement,text:e.target.value}})}/></label>}<p className="text-sm text-muted">El menú público muestra Inicio, Productos y Categorías automáticamente.</p></>}
 {section==="inicio"&&<HomeSectionsEditor sections={draft.publicPageConfig.homeSections} categories={categories} products={products} onChange={homeSections=>page({homeSections})} onImage={pickSectionImage} editingSectionId={homeEditingSectionId} onEditingSectionChange={setHomeEditingSectionId}/> }
 {section==="productos"&&<><label>Columnas en celulares<select className="field" value={draft.mobileProductColumns} onChange={e=>update({mobileProductColumns:Number(e.target.value) as 1|2})}><option value={1}>1 columna</option><option value={2}>2 columnas</option></select></label><label>Formato de imágenes<select className="field" value={draft.designConfig.productImageRatio} onChange={e=>design({productImageRatio:e.target.value as "square"|"portrait"})}><option value="portrait">Vertical (4:5)</option><option value="square">Cuadrado (1:1)</option></select></label><label>Ajuste de imagen<select className="field" value={draft.designConfig.productImageFit} onChange={e=>design({productImageFit:e.target.value as "contain"|"cover"})}><option value="cover">Rellenar</option><option value="contain">Mostrar completa</option></select></label><label>Bordes: {draft.designConfig.cardRadius}px<input type="range" min={0} max={32} value={draft.designConfig.cardRadius} onChange={e=>design({cardRadius:Number(e.target.value)})}/></label>{toggle("Habilitar botón de compra rápida",draft.designConfig.quickBuyEnabled,quickBuyEnabled=>design({quickBuyEnabled}))}{toggle("Mostrar botón flotante del carrito en la tienda pública",draft.designConfig.floatingCartEnabled,floatingCartEnabled=>design({floatingCartEnabled}))}{toggle("Mostrar SKU",draft.designConfig.showSku,showSku=>design({showSku}))}</>}
 {section==="pie"&&<><label>Texto del pie<textarea className="field" maxLength={240} value={draft.designConfig.footerText} onChange={e=>design({footerText:e.target.value})}/></label>{toggle("Mostrar menú",draft.designConfig.footerOptions.showMenu,showMenu=>design({footerOptions:{...draft.designConfig.footerOptions,showMenu}}))}<h3>Opciones adicionales</h3>{toggle("Mostrar medios de pago",draft.designConfig.footerOptions.showPaymentMethods,showPaymentMethods=>design({footerOptions:{...draft.designConfig.footerOptions,showPaymentMethods}}))}{toggle("Mostrar medios de envío",draft.designConfig.footerOptions.showDeliveryMethods,showDeliveryMethods=>design({footerOptions:{...draft.designConfig.footerOptions,showDeliveryMethods}}))}{toggle("Mostrar datos de contacto",draft.designConfig.footerOptions.showContact,showContact=>design({footerOptions:{...draft.designConfig.footerOptions,showContact}}))}{toggle("Mostrar redes sociales",draft.designConfig.footerOptions.showSocials,showSocials=>design({footerOptions:{...draft.designConfig.footerOptions,showSocials}}))}{draft.designConfig.footerOptions.showSocials&&(["instagram","tiktok","facebook"] as const).map(key=><label key={key} className="capitalize">{key}<input className="field normal-case" type="url" placeholder="https://" value={draft.publicPageConfig.socials[key]} onChange={e=>page({socials:{...draft.publicPageConfig.socials,[key]:e.target.value}})}/></label>)}</>}
 {section==="plantilla"&&<><p className="text-sm text-muted">Cada plantilla tiene su propia estructura, colores y tipografía. Tus imágenes, productos y textos se conservan. Los cambios se ven en tu tienda recién al publicar.</p>{[...new Set([...publicStoreTemplates,draft.template])].map(template=><button type="button" aria-pressed={draft.template===template} className={"design-template-card "+(draft.template===template?"selected":"")} key={template} onClick={()=>update({template,useTemplateColors:true,designConfig:{...draft.designConfig,font:"template"}})}><span className="design-template-mini" data-template={template} aria-hidden="true"><span className="mini-announcement"/><span className="mini-header"><i/><strong>{template.toUpperCase()}</strong><i/></span><span className="mini-navigation"/><span className="mini-hero">{images.hero[0]&&<img src={images.hero[0].url} alt=""/>}<span>Nueva colección<small>Descubrila</small></span></span><span className="mini-products"><i/><i/><i/><i/></span></span><span className="design-template-caption"><strong>{storeTemplateLabels[template]}</strong><span>{draft.template===template?"✓ Elegida":"Elegir"}</span></span><small>{template==="roma"?"Logo centrado · Portada contenida · Carrusel mobile":template==="dana"?"Doble encabezado · Portada amplia · Tipografía editorial":template==="vene"?"Logo a la izquierda · Portada amplia · Grilla mobile":"Diseño anterior de tu tienda"}</small></button>)}</>}
 </div></aside><footer className="design-mobile-footer"><button type="button" className="design-mobile-edit" aria-controls="design-controls" aria-expanded={mobileEditorOpen} onClick={openMobileEditor}><Paintbrush size={17} aria-hidden="true"/>Editar</button></footer><section className="design-preview" aria-label="Vista previa de la tienda"><header><span>Vista previa · sin compras reales</span><div><button type="button" className={device==="desktop"?"active":""} aria-label="Vista previa escritorio" aria-pressed={device==="desktop"} onClick={()=>setDevice("desktop")}><Monitor size={18}/></button><button type="button" className={device==="mobile"?"active":""} aria-label="Vista previa celular" aria-pressed={device==="mobile"} onClick={()=>setDevice("mobile")}><Smartphone size={18}/></button><button type="button" className="design-preview-mode" aria-pressed={preview} onClick={()=>setPreview(!preview)}>{preview?"Editar diseño":"Vista previa"}</button></div></header><div className={"design-frame "+device}><iframe ref={frame} title="Vista previa de la tienda" src="/vista-previa/tienda" onLoad={sendPreview}/></div></section></div></div>;
}
